extension_dir = "ext"

; These are loaded as external DLLs
extension=openssl
extension=pdo_sqlite
extension=sqlite3
extension=mbstring
extension=fileinfo
extension=curl
extension=intl
extension=sodium

; These are built-in to php8ts.dll — do NOT load as extensions
; dom, xml, bcmath, ctype, phar, iconv, tokenizer, json, simplexml
; xmlwriter, xmlreader are all compiled in

memory_limit = 256M
max_execution_time = 60
date.timezone = Asia/Manila
